# This section blueprint defines a pages section that can be reused across multiple blueprints
# or multiple times within the same blueprint, see `/site/blueprints/pages/notes.yml` and `/site/blueprints/site.yml`
# Sections can have different layouts and display additional information or a preview image
# More about pages sections: https://getkirby.com/docs/reference/panel/sections/pages
type: pages
label: Kitchen Sinks
parent: kirby.page("kitchensinks")
sortBy: date desc
template: kitchensink
empty: No kitchen sinks yet
create:
  - kitchensink
templates:
  - kitchensink
info: "{{ page.published }}"
columns:
  textfield:
    label: Textfield
    type: text
  int:
    label: Numberfield
    type: number
    align: right
image:
  query: page.images.first
  cover: true

