title: Post
num: date
create:
  fields:
    - subheading
columns:
  main:
    width: 2/3
    fields:
      bodyContent: fields/bodyContent

  sidebar:
    width: 1/3
    sections:
      fields:
        type: fields
        fields:
          meta: fields/meta
      files: sections/files


