label: Layout
fields:
  layoutField:
    type: layout
    layouts:
      - "1/1"
      - "1/2, 1/2"
      - "1/4, 1/4, 1/4, 1/4"
      - "1/3, 2/3"
      - "2/3, 1/3"
      - "1/3, 1/3, 1/3"
      - "1/1, 1/3, 2/3"
      - "1/1, 2/3, 1/3"
      - "1/2, 1/2, 1/3, 1/3, 1/3"
    fieldsets:
      - heading
      - text
      - image
      - quote
      pages:
        label: "{{ pages.length }} pages"
        preview: fields
        wysiwyg: true
        fields:
          pages:
            extends: fields/pages
            layout: cardlets
            image:
              cover: true
    settings:
      fields:
        class:
          type: text
          width: 1/2
        id:
          type: text
          width: 1/2
        image:
          label: Background image
          type: files
          width: 1/2
        color:
          label: Background color
          type: color
          mode: options
          width: 1/2
          options:
            "Sunny rays": "#F8B195"
            "First-love blush": "#F67280"
            "Cherry blossom": "#C06C84"
            "Morning gloom": "#6C5B7B"
            "Midnight rain": "#355C7D"
    pretty: true
